apiVersion: v1
kind: Namespace
metadata:
  name: helios01-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: helios01-ns-quota
  namespace: helios01-ns
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 30Gi
    limits.cpu: "10"
    limits.memory: 32Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helios-sa
  namespace: helios01-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: helios01-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: helios-sa
  namespace: helios01-ns
---
